server:
  port: 8001
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tb_employee
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: "employee"